DF-1575: add update data script example
tradingview-pine-seeds/docs pull request #20
Opened 2023-01-20 16:52 UTC by pavel-rusinov

2023-01-26 07:49 UTC, osal requested changes

2023-01-26 07:49 UTC, osal commented on update_example/update_santiment.py
> +from santiment api and save updates to csv files in required format"""
Надо все аббревиатуры писать большими буквами (CSV, API)
Также Bitcoin, Ethereum
Нужна также ссылка на API.
И скрипт у нас не сохраняет апдейты, а конвертирует данные.
This script downloads data from Santiment API, converts it to Pine Seeds historical data format and saves it as CSV files.

2023-01-26 07:49 UTC, osal commented on update_example/update_santiment.py
> +    data_filename_prefix: str
Что такое Slug? Я бы переименовал или объяснил что это и откуда берется в комментарии. Лучше подобрать другой термин по смыслу.

2023-01-26 07:49 UTC, osal commented on update_example/update_santiment.py
> +DATA_FILENAME_POSTFIX_FIXES = {
слово postfix везде меняем на suffix

2023-01-26 07:49 UTC, osal commented on update_example/update_santiment.py
> +DATA_FOLDER = "../seed_crypto_santiment/data/seed_crypto_santiment/"
вот это я бы вынес в параметр скрипта, по умолчанию "."

2023-01-26 07:49 UTC, osal commented on update_example/update_santiment.py
> +    data_filename_prefix: str
а нам тут точно классы нужны? может обойдемся списком кортежей?
скрипт должен быть максимально простым

2023-01-26 07:49 UTC, osal commented on update_example/update.sh
> +git push
Вот этот sh не нужен. Надо это описать в документе update_example.md как последовательность действий по шагам, причем максимально подробно. Указать что понадобиться питон, такой-то версии, дать ссылку на инструкцию по установке. Указать что понадобится git, дать ссылку на инструкцию по установке. 
Если выполняются команды в консоли, нужно текстом команду показать, чтобы ее можно было скопировать, и еще и вывод команды приложить (в виде скриншота)
- сохранить скрипт из примера в файл (скриншот, интерфейс гитхаба)
- выписать условный форк репозитория (git clone) в папку (команда + скриншот) 
- запустить скрипт с указанием папки (команда + скриншот)
- показать git diff (команда + скриншот)
- git add (команда + скриншот)
- git commit (команда + скриншот)
- git push (команда + скриншот)
и в конце привести скриншот что произошло после пуша (что создался PR и он был смержен и т.д.)

2023-01-26 07:49 UTC, osal commented on update_example/update_santiment.py
> +    filename_postfix = DATA_FILENAME_POSTFIX_FIXES.get(metric, metric)
вот этот фикс суффикса давай уберем - лишнее усложнение

2023-01-26 07:49 UTC, osal commented on update_example/update_example.md
> +This script requests several metric values for 2 crypto assets: ethereum and bitcoin. For each crypto asset metric, a file \<CRYPTO_ASSET_FILE_PREFIX>_<METRIC_OR_FIXED_POSTFIX>.csv is updated (e. g.
про фикс суффикса написал в коментариях к коду

2023-01-26 07:49 UTC, osal commented on update_example/update_example.md
> +For each crypto asset metric we make http request to santiment graphql api (we request all data up to today inclusive) and save updated values to corresponding file. If there is a value for a date in
HTTP, Santiment, GraphQL API и т.д. Надо использовать заглавные буквы для аббревиатур и имен собственных.

2023-01-26 07:49 UTC, osal commented on update_example/update_santiment.py
> +    orig = {}
давай переменные называть по возможности без сокращений

2023-01-26 07:49 UTC, osal commented on update_example/update_santiment.py
> +REQ_BODY_TEMPLATE = """
REQ -> REQUEST

2023-01-26 07:49 UTC, osal commented on update_example/update.sh
> +git push
как пример подобной инструкции с командами и выводом их 
https://phoenixnap.com/kb/how-to-install-git-on-ubuntu

2023-01-26 11:54 UTC, pavel-rusinov commented on update_example/update_santiment.py
> +REQ_BODY_TEMPLATE = """
поправил

2023-01-26 11:57 UTC, pavel-rusinov commented on update_example/update_santiment.py
> +    orig = {}
поправил

2023-01-26 12:05 UTC, pavel-rusinov commented on update_example/update_example.md
> +For each crypto asset metric we make http request to santiment graphql api (we request all data up to today inclusive) and save updated values to corresponding file. If there is a value for a date in
поправил

2023-01-26 12:09 UTC, pavel-rusinov commented on update_example/update_santiment.py
> +    filename_postfix = DATA_FILENAME_POSTFIX_FIXES.get(metric, metric)
поправил

2023-01-26 12:09 UTC, pavel-rusinov commented on update_example/update_example.md
> +This script requests several metric values for 2 crypto assets: ethereum and bitcoin. For each crypto asset metric, a file \<CRYPTO_ASSET_FILE_PREFIX>_<METRIC_OR_FIXED_POSTFIX>.csv is updated (e. g.
поправил

2023-01-26 13:20 UTC, pavel-rusinov commented on update_example/update_santiment.py
> +DATA_FILENAME_POSTFIX_FIXES = {
поправил

2023-01-26 13:31 UTC, pavel-rusinov commented on update_example/update_santiment.py
> +    data_filename_prefix: str
это в santiment api используется имя поля slug для монеты
объекты же более читаемые при использовании, чем кортежи

2023-01-26 13:31 UTC, pavel-rusinov commented on update_example/update_santiment.py
> +    data_filename_prefix: str
переименовал, добавил коммент

2023-01-26 13:52 UTC, pavel-rusinov commented on update_example/update_santiment.py
> +from santiment api and save updates to csv files in required format"""
поправил

2023-01-26 16:38 UTC, pavel-rusinov commented on update_example/update.sh
> +git push
добавил
наверно, нужно и для windows с mac такие же инструкции написать

2023-01-27 06:32 UTC, osal commented on update_example/update_santiment.py
> +    data_filename_prefix: str
все-таки я настаиваю что нужно убрать объекты, т.к. этот пример не для программистов

2023-01-27 10:56 UTC, pavel-rusinov commented on update_example/update_santiment.py
> +    data_filename_prefix: str
поправил

2023-01-27 14:25 UTC, pavel-rusinov commented on update_example/update_santiment.py
> +    for slug_info in COIN_INFOS:
atelnov сказал, coin назватьпоправил

2023-01-27 14:25 UTC, pavel-rusinov commented on update_example/update_example.md
> +
поправил

2023-01-31 06:55 UTC, ggalimzyanova commented on update_example/update_example.md
> +1. Save update_santiment.py script to your computer: click on "Copy raw cantents" button on github page with opened script, then open text editor on your computer, right-click in it and press "Paste"
слишком сложно описано сохранение, я не сразу поняла, надо либо переписать более понятно или поменять шаги, так как мне кажется это проще:
открыть файл со скриптом на гитхаб
нажать raw
откроется новое окно с файлом и там просто нажать Save as
откроется меню для сохранения файла, название файла уже будет update_santiment.py

2023-01-31 06:56 UTC, ggalimzyanova commented on update_example/update_example.md
> +    ![Copy raw contents](/images/copy_raw_contents.png)
скриншот не очень помогает найти кнопку Copy raw contents

2023-01-31 06:59 UTC, ggalimzyanova commented on update_example/update_example.md
> +2. Clone your repository fork to your computer `git clone <your_repository.git>`. You can get repo name for clone command by clicking "Code" and then "Copy to clipboard", then paste it to command
если надо копировать именно ssh, а не https или вообще github CLI, надо уточнить, потому что например у меня при нажатии на code открывается https

2023-01-31 07:05 UTC, ggalimzyanova commented on update_example/update_example.md
> +6. You can run `git status` to see which files have changed. If it is not the first update, you can see what changed in files by running `git diff`. Press 'q' to close diff.
You can run `git status` to see which files have changed
надо ли указывать, что файлы не только могут измениться, но и могут добавиться новые? в этом случае надо ещё в symbol_info новые символы дописать

2023-01-31 07:09 UTC, ggalimzyanova commented on update_example/update_example.md
> +This script requests several metric values for 2 crypto assets: Ethereum and Bitcoin. For each crypto asset metric, a file \<CRYPTO_ASSET_FILE_PREFIX>_<METRIC_SUFFIX>.csv is updated (e. g. for Bitcoi
можно было бы поделить на отдельные пукнты, одним полотном сложно воспринимать
ещё было бы хорошо привести кусочки кода, которые отвечают за описанный пункт
или перенести это описание отсюда в сам скрипт комментариями в нужные места, а тут указать, что "если хотите понять, как рабоает скрипт, читайте комментарии"

2023-02-01 07:03 UTC, eknesterova commented on update_example/update_example.md
> +1. Save update_santiment.py script to your computer: click on "Copy raw cantents" button on github page with opened script, then open text editor on your computer, right-click in it and press "Paste"
Согласна с Гулюсой, ее вариант описания проще для понимания. А у меня вообще нет кнопки "Copy raw cantents" - ни в той же строчке, где кнопки Raw и Blame, ни в выпадающем меню

2023-02-01 07:11 UTC, eknesterova commented on update_example/update_example.md
> +    ![Copy raw contents](/images/copy_raw_contents.png)
Особенно если ее нет (возможно, это зависит от настроек гитхаба)

2023-02-01 07:13 UTC, eknesterova commented on update_example/update_example.md
> +2. Clone your repository fork to your computer `git clone <your_repository.git>`. You can get repo name for clone command by clicking "Code" and then "Copy to clipboard", then paste it to command
У меня тоже открывается https, но я склонировала с помощью ssh (ключ не был настроен и дополнительно нужно было выполнить настройку - было бы хорошо и это включить в описание или лучше дать ссылку на официальную документацию Гитхаба по этой теме)

2023-02-01 07:14 UTC, eknesterova commented on update_example/update_example.md
> +6. You can run `git status` to see which files have changed. If it is not the first update, you can see what changed in files by running `git diff`. Press 'q' to close diff.
Да, в моем случае были добавлены два новых: Untracked files:
  (use "git add <file>..." to include in what will be committed)
	data/seed_crypto_santiment/BTC_UNIQUE_SOCIAL_VOLUME_TOTAL_1H.csv
	data/seed_crypto_santiment/ETH_UNIQUE_SOCIAL_VOLUME_TOTAL_1H.csv

2023-02-01 07:16 UTC, eknesterova commented on update_example/update_example.md
> +This script requests several metric values for 2 crypto assets: Ethereum and Bitcoin. For each crypto asset metric, a file \<CRYPTO_ASSET_FILE_PREFIX>_<METRIC_SUFFIX>.csv is updated (e. g. for Bitcoi
Да, было бы хорошо разбавить это полотно

2023-03-01 16:25 UTC, merged